version: "3"

services:
  web:
    build: .
    command: python -B manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - django
networks:
  django:
   driver: bridge
   

