# Generated by Django 3.1.3 on 2021-05-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('location_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('location_long', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=150, null=True)),
                ('location_country', models.CharField(blank=True, max_length=70, null=True)),
                ('location_state', models.CharField(blank=True, max_length=50, null=True)),
                ('location_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('location_continent', models.CharField(blank=True, max_length=20, null=True)),
                ('location_complement', models.CharField(blank=True, max_length=200, null=True)),
                ('location_date', models.DateTimeField(blank=True, null=True)),
                ('location_hostname', models.CharField(blank=True, max_length=150, null=True)),
                ('location_organization', models.CharField(blank=True, max_length=150, null=True)),
                ('location_time_zone', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
