# Generated by Django 3.1.7 on 2021-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStatistic',
            fields=[
                ('photo_statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_statistic_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photo_statistic',
                'managed': False,
            },
        ),
    ]
