# Generated by Django 3.1.3 on 2021-05-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('error_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('error_type_title', models.CharField(blank=True, max_length=100, null=True)),
                ('error_type_code', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'error_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAccess',
            fields=[
                ('log_access_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_data_information_id', models.BigIntegerField(blank=True, null=True)),
                ('log_access_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('error_log', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='log.errortype')),
                ('error_type_id', models.BigIntegerField(blank=True, null=True)),
                ('error_log_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'error_log',
                'managed': False,
            },
        ),
    ]
