# Generated by Django 3.1.3 on 2021-05-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDataInformation',
            fields=[
                ('system_data_information_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_data_information_local_storage', models.CharField(blank=True, max_length=1000, null=True)),
                ('system_data_information_cookies', models.CharField(blank=True, max_length=1000, null=True)),
                ('system_data_information_user_agent', models.CharField(blank=True, max_length=150, null=True)),
                ('system_data_information_http_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('system_data_information_http_referer', models.CharField(blank=True, max_length=100, null=True)),
                ('system_data_information_remote_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('system_data_information_date', models.DateTimeField(blank=True, null=True)),
                ('system_data_information_host_name', models.CharField(blank=True, max_length=100, null=True)),
                ('system_data_information_host_name_by_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('system_data_information_ip_by_host_name', models.CharField(blank=True, max_length=100, null=True)),
                ('system_data_information_http_x_forwarded_for', models.CharField(blank=True, max_length=150, null=True)),
                ('system_data_information_device_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'system_data_information',
                'managed': False,
            },
        ),
    ]
