# Generated by Django 3.1.3 on 2021-05-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('follower_id', models.AutoField(primary_key=True, serialize=False)),
                ('follower_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'follower',
                'managed': False,
            },
        ),
    ]
