# Generated by Django 3.1.3 on 2021-05-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210507_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMarketing',
        ),
        migrations.DeleteModel(
            name='EmailMonetization',
        ),
    ]
