# Generated by Django 3.1.3 on 2021-05-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210507_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='error_log',
        ),
        migrations.DeleteModel(
            name='LogAccess',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.DeleteModel(
            name='ErrorType',
        ),
    ]
