# Generated by Django 3.1.3 on 2021-05-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210507_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
