# Generated by Django 3.1.3 on 2021-05-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
