# Generated by Django 3.1.3 on 2021-05-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemDataInformation',
        ),
    ]
