# Generated by Django 3.1.3 on 2021-05-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMarketing',
            fields=[
                ('email_marketing_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_marketing_email', models.CharField(blank=True, max_length=100, null=True)),
                ('email_marketing_description', models.CharField(blank=True, max_length=150, null=True)),
                ('email_marketing_sent', models.BooleanField(blank=True, null=True)),
                ('email_marketing_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'email_marketing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailMonetization',
            fields=[
                ('email_monetization_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('full_name_guest', models.CharField(blank=True, max_length=200, null=True)),
                ('email_guest', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_send', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_monetization',
                'managed': False,
            },
        ),
    ]
