# Generated by Django 3.1.3 on 2021-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'like',
                'managed': False,
            },
        ),
    ]
