# Generated by Django 3.1.3 on 2021-05-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_post_date', models.DateTimeField()),
                ('photo_url', models.TextField()),
                ('photo_description', models.TextField(blank=True, null=True)),
                ('photo_allow_comments', models.IntegerField()),
                ('photo_likes', models.BigIntegerField()),
                ('photo_comments', models.BigIntegerField(blank=True, null=True)),
                ('photo_public', models.BigIntegerField(blank=True, null=True)),
                ('photo_styles', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'photo',
                'managed': False,
            },
        ),
    ]
